# http://www.lmn.org/philippines/wordpress/?page_id=1086
# http://www.lmn.org/philippines/galery_2/main.php


inc:
  # Blog Information
  title:        "Laymen Ministries Philippines"
  subtitle:     "God's work among the natives in Mindoro"
  cover-image:  /assets/img/cover/kaupawan.jpg
  logo:         /assets/img/lmp-logo.svg

  # Company information
  company:      LMP
  url:          http://lmphilippines.org/
  facebook:     false
  twitter:      false
  gplus:        false
  about_link:   /about/

  # Product Information
  # product_link: http://incorporated.sendtoinc.com/
  # tagline:      "Get a modern blog for your company"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Crimson+Text:600|Raleway:400,600'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         //lmphilippines.org
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
timezone:    nil

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Image directories
article_img_dir: /images/articles
wp_img_dir:      /images/wp-uploads
img_dir:         /images

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: rouge

# permalink:     pretty
permalink:     /:year/:month/:day/:title.html
paginate_path: page:num
paginate:      10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        localhost
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  # coderay:
  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style

redcloth:
  hard_breaks: true

sass:
  sass_dir: _sass
  style: compressed

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
# assets:

#   dirname: assets
#   baseurl: /assets/
#   sources:
#     - _assets/js
#     - _assets/css
#     - _assets/img
#   js_compressor: uglifier
#   css_compressor: sass
#   # cachebust: none
#   # cache: false
#   gzip: [ text/css, application/javascript ]
#   debug: false

inlcude:

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - node_modules
  - serve.command
  - serve.sh
  - sync.sh

plugins:
  - jekyll-paginate
  # - jekyll-assets

menu:
  -
    label: "About Us"
    url: /about-us/
    menu:
      -
        label: "Laymen Ministries"
        url: /lmp/
      -
        label: "Katutubo Excel Schools Inc."
        url: /kesi/
      -
        label: "Sablayan Prison Ministry"
        url: /prison-ministry/
  -
    label: "Get Involved"
    url: /get-involved/
  -
    label: "Support Us"
    url: /support-us/
  -
    label: "Videos"
    url: /videos/
  -
    label: "Gallery"
    url: http://gallery.lmphilippines.org




